// Initial form data configurations
export const formsConfig = {
  signUp: {
    firstname: "",
    lastname: "",
    dateOfBirth: "",
    street: "",
    zipCode: "",
    city: "",
    country: "",
    phone: "",
    email: "",
    password: "",
    confirmPassword: "",
  },
  editProfile: {
    firstname: "",
    lastname: "",
    street: "",
    city: "",
    zipCode: "",
    country: "",
    phone: "",
    dateOfBirth: "",
  },
  signIn: {
    email: "",
    password: "",
  },
  resetPassword: {
    email: "",
  },
  alternativeAddress: {
    firstname: "",
    lastname: "",
    street: "",
    zipCode: "",
    city: "",
    country: "",
    phone: "",
  },
  contact: {
    firstname: "",
    lastname: "",
    email: "",
    phone: "",
    orderNumber: "",
    subject: "",
    message: "",
  },
  payment: {
    cardName: "",
    cardNumber: "",
    expiryMonth: "",
    expiryYear: "",
    paymentMethod: "",
    cvv: "",
    billingAddress: "",
  },
};
